### ISSUE TITLE
Ability to Give Upvotes or Kudos

### ISSUE THREAD

**Issue by ryanzbartlett** [jamfluencer/web#2]
Did that song slap? Hit a button to grant your fellow Jam contributor a sick, sick internet point in the form of one Jam Jar!

Could be possible to gamify it a bit by limiting users to something like 10 Jam Jars per Jam that they can dole out as they wish, and have some sort of leaderboard showing who's received the most jars?

Counterpoint, I don't want to 'competition' it too much, and want to avoid incentivizing the selection of crowd-pleasing music to get jars. The integrity of the Jam is at stake here.

So maybe no leaderboard, but I do like the idea of the Jam Jars so maybe its unlimited but we include stats on most Jam Jars in the Jam Preserves™ (which is what I want to call our Wrapped)?

I think each person should be allowed to give one Jam Jar per track. Like upvotes on Stackoverflow. I think users should be able to see their totals, and possibly make it visible per week. I think we'll control the culture, and in such we'll just not make it competitive. It's just a thumbs up.

If we want this to work with #1  we'll need it to tell the user that they gave kudos, but delay when it displays. Otherwise you can figure out who added what track by granting kudos.

**Comment by marshall-davis** [comment]
The backend now how an endpoint to support this (see the Bruno collection) and dispatches an event when it does so.

```
{
  "track_id": string,
  "playlist_id": ?string,
  "from_user_id": null, // currently always null
  "for_user_id": null, // currently always null
  "for_spotify_account_id": string,
  "created_at": string, // Y-m-d H:i:s
}
```
